### ISSUE TITLE
Compilation creates invalid binary : Assertion failed

### ISSUE THREAD

**Issue by tissatussa** [Mergener/illumina#54]
i just tried to compile your v1.0 source code but it created an invalid binary, although the compilation went well :

```
~/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin$ ./cmake .
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Generating build files for version dev-05bb8f62f7aa23c89d4f45e16f36cef48f2922a9 on configuration .
-- Configuring done (0.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/roelof/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin

(base) roelof@roelof-HP-Elite-x2-1012-G2:~/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin$ make illumina_cli_avx2
[  4%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/types.cpp.o
[  9%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/illumina.cpp.o
[  9%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/board.cpp.o
[ 14%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/zobrist.cpp.o
[ 19%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/parsehelper.cpp.o
[ 23%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/attacks.cpp.o
[ 28%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/perft.cpp.o
[ 33%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/transpositiontable.cpp.o
[ 38%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/search.cpp.o
[ 42%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/evaluation.cpp.o
[ 42%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/timemanager.cpp.o
[ 47%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/boardutils.cpp.o
[ 52%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/utils.cpp.o
[ 57%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/pext_attacks.cpp.o
[ 61%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/magic_attacks.cpp.o
[ 66%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/tunablevalues.cpp.o
[ 71%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/endgame.cpp.o
[ 76%] Building CXX object illumina/CMakeFiles/illumina_lib_avx2.dir/nnue.cpp.o
[ 76%] Linking CXX static library libillumina_avx2.a
[ 76%] Built target illumina_lib_avx2
[ 80%] Building CXX object cli/CMakeFiles/illumina_cli_avx2.dir/main.cpp.o
[ 85%] Building CXX object cli/CMakeFiles/illumina_cli_avx2.dir/cliapplication.cpp.o
[ 90%] Building CXX object cli/CMakeFiles/illumina_cli_avx2.dir/commands.cpp.o
[ 95%] Building CXX object cli/CMakeFiles/illumina_cli_avx2.dir/state.cpp.o
[ 95%] Building CXX object cli/CMakeFiles/illumina_cli_avx2.dir/ucioption.cpp.o
[100%] Linking CXX executable illumina_avx2
[100%] Built target illumina_cli_avx2

(base) roelof@roelof-HP-Elite-x2-1012-G2:~/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin$ ./cli/illumina_avx2 
illumina_avx2: /home/roelof/Apps/Cmake/cmake-3.29.2-linux-x86_64/bin/illumina/types.h:128: illumina::ui8 illumina::lsb(illumina::ui64): Assertion `n != 0' failed.
Aborted (core dumped)
```

i used cmake version 3.29.2
btw. i had to clone the source code by the command `git clone https://github.com/Mergener/illumina.git --recursive` otherwise i had other errors (compiling the supplied ZIPped source was impossible).

i tried to remove the concerning 'ILLUMINA_ASSERT()' line, but then other errors like `Assertion 'n != 0' failed` arose.

Note: the supplied asset binary runs fine in CuteChess GUI.

[ i'm on Xubuntu 22.04 ]

**Comment by Mergener** [comment]
Hi @tissatussa! Thanks for the issue. I still need to debug some of these assertions. Having said that, assertions are only active on debug builds. You can build on Release mode with DCMAKE_BUILD_TYPE=Release.

**Comment by tissatussa** [comment]
> ..You can build on Release mode with DCMAKE_BUILD_TYPE=Release..

i'll try (you should mention such compilation option in the README :-)

**Comment by Mergener** [comment]
I've removed/fixed the assertions that were triggering errors as soon as the program started. Also, as suggested, I've added some instructions in the Readme that cover CMake build types. Once again, thank you for the Issue, and feel free to reopen another or come back to this one if other problems arise!

**Comment by tissatussa** [comment]
thanks, now compilation succeeded but only after a few actions .. at first i downloaded the ZIPped source and tried to compile with `cmake -DCMAKE_BUILD_TYPE=Release -DTUNING=ON`, then this error occurred :

```
[...]
CMake Error at ext/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    [..]/ext/litetest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
```

i solved this error by cloning the source with option `--recursive` : this way the missing files are included and `cmake` could create a Makefile without errors or warnings .. however, compilation with `make` gave an error :

```
[..]/state.cpp:304:41: error: ‘INT_MIN’ was not declared in this scope
  304 |                               int min = INT_MIN,
      |                                         ^~~~~~~
[..]/cli/state.cpp:12:1: note: ‘INT_MIN’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
```

indeed, when adding `#include <climits>` on top of `/cli/state.cpp` the source was OK and compilation went well : it created a valid binary of 3.1 Mb which runs fine in CuteChess GUI !

**Comment by Mergener** [comment]
Thanks once again! The file you specified used to compile with MinGW and I didn't try to create a tuning build for Linux, so this was a good catch. As for the `--recursive` flag, are you having problems building the engine executable itself or only the tests executable? If only the tests are failing, this is expected behavior and was specified in the readme, although I've edited it to be a little bit clearer now. If not, then something's wrong in Illumina's build pipeline.

**Comment by tissatussa** [comment]
> ..I didn't try to create a tuning build for Linux, so this was a good catch..

yes, i'm only on Linux .. i don't know `MinGW`, it must be a Window$ thingy

> As for the --recursive flag, are you having problems building the engine executable itself or only the tests executable?

finally i only used the avx2 executable, the other (test) binaries don't interest me .. without using the --recursive flag no Makefile is created, so i can't build the executable.
